### ISSUE TITLE
1 - Git branches

### ISSUE THREAD

**Issue by khamusa** [hayelleon/munchkin_game#1]
Objetivo: aprender a trabalhar com branches (ramos) do git.

Você deve aprender como trabalhar com branches no git. Busque tutoriais, cursos e materias online!

Resumo de comandos básicos para lidar com branches no git
   - `git branch` - lista os branches existentes. O Branch em que você está no momento terá um * na frente.
   - `git branch nomedobranch` - cria um branch chamado `nomedobranch`. Quando esse branch é criado ele tem exatamente o mesmo conteúdo do branch em que você estava. Ou seja, onde você está no momento em que você cria um novo branch é importante.
   - `git checkout nomedobranch` - vai para o branch `nomedobranch`. A partir deste momento todos os commits que você fizer serão registrados nesse outro ramo.
   - `git checkout -b nomedeumoutrobranch` - atalho para criar um novo branch e ir para ele de uma vez só.
   - `git branch -d nomedobranch` - apaga o branch nomedobranch

 Esercício:
1. Criar um branch "primeiro-branch". Neste branch, adicione um arquivo "meu-nome-completo.txt", e escreva "Marko Pemonuceno" (errado mesmo). Faça o commit e envie esse branch para o github (o comando para enviar para o github é o `git push`).
2. Volte para o branch master;
3. Crie um branch "segundo-branch". Neste branch, adicione um arquivo "meu-endereco-completo.txt", e adicione seu endereço. Faça o commit e envie o branch para o github;
4. Na interface do github, vá na seção Pull requests. Descubra como abrir uma pull request para cada um desses branchs que você enviou. Lembre que a Pull request é um "pedido de incorporação". Você deve  criar duas PRs pedindo que as modificações sugeridas sejam incorporadas no branch master.
5. Me avise que vou verificar as pull Requests e vamos continuar a partir dali, interagindo pela interface do github.

Boa referência: https://git-scm.com/book/pt-br/v1/Ramifica%C3%A7%C3%A3o-Branching-no-Git-B%C3%A1sico-de-Branch-e-Merge

**Comment by hayelleon** [comment]
Feito

**Comment by khamusa** [comment]
@hayelleon fiz o `merge` das duas PRs. Isso significa que agora o branch `master` aqui do github está à frente do que você tem na sua máquina. Você agora precisa atualizar o seu branch master:

```
git checkout master
git pull --rebase
```

Isso vai puxar as modificações remotas pro seu branch local e equiparar sua versão local

Veja que agora você tem os dois arquivos no mesmo branch master. Abra uma nova PR (em um novo branch) para corrigir o seu nome, que está com `k`.

**Comment by hayelleon** [comment]
@khamusa Acho que feito! XD

**Comment by khamusa** [comment]
Legal, vou fechar o issue!
